Controllers/CMSController.cs
using AuthSystem.Areas.Identity.Data;
using AuthSystem.Models;
using CMS.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http.Headers;
using System.Data;
using AuthSystem.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Options;
using AuthSystem.Services;
using System.Text;
using System;
using AuthSystem.Manager;
using _CMS.Manager;
using ExcelDataReader;
using AOPC_CMSv2.ViewModel;
using static AOPC.Controllers.VendorController;
using System.Collections.Generic;

namespace AOPC.Controllers
{
    public class CMSController : Controller
    {
        string status = "";
        private readonly QueryValueService token;
        private readonly AppSettings _appSettings;
        private ApiGlobalModel _global = new ApiGlobalModel();
        private GlobalService _globalService;
        DbManager db = new DbManager();
        public readonly QueryValueService token_;
        private readonly UserManager<ApplicationUser> _userManager;
        private IConfiguration _configuration;
        private string apiUrl = "http://";

        public CMSController(IOptions<AppSettings> appSettings, GlobalService globalService,
                  UserManager<ApplicationUser> userManager, QueryValueService _token,
                  IHttpContextAccessor contextAccessor,
                  IConfiguration configuration)
        {
            _userManager = userManager;
            token_ = _token;
            _configuration = configuration;
            apiUrl = _configuration.GetValue<string>("AppSettings:WebApiURL");
            _appSettings = appSettings.Value;
        }

        public async Task<String> GetCorporate()
        {

            var url = DBConn.HttpString + "/api/ApiCorporatePrivilege/CorporatePrivilegeLsit";
            HttpClient client = new HttpClient();
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue(token_.GetValue());
            string response = await client.GetStringAsync(url);

            return response;
        }
        //try


        [HttpGet]
        public async Task<JsonResult> GetCorp()
        {
            string response = await GetCorporate();
            List<CorporatePrivilegeVM> models = JsonConvert.DeserializeObject<List<CorporatePrivilegeVM>>(response);
            return new(models);
        }
        [HttpGet]
        public async Task<JsonResult> getTopCorp()
        {
            string response = await GetCorporate();

            List<TopCorporateVM> models = JsonConvert.DeserializeObject<List<TopCorporateVM>>(response);
            var result = new List<TopCorporateVM>();
            for (int x = 0; x < models.Count; x++)
            {
                var item = new TopCorporateVM();
                item.Corporatename = models[x].Corporatename;
                item.NoOfVisit = models[x].NoOfVisit;
                result.Add(item);
            }
            return new(result);
        }

        public class AuditTrailPaginationModel
        {
            public string? CurrentPage { get; set; }
            public string? NextPage { get; set; }
            public string? PrevPage { get; set; }
            public string? TotalPage { get; set; }
            public string? PageSize { get; set; }
            public string? TotalRecord { get; set; }
            public List<Audittrailvm> items { get; set; }


        }
        public class AuditFullName
        {
            public string FullName { get; set; }
        }
        [HttpPost]
        public async Task<IActionResult> GetAuditSearch(AuditFullName data)
        {
            string result = "";
            var list = new List<Audittrailvm>();
            try
            {
                HttpClient client = new HttpClient();
                var url = DBConn.HttpString + "/api/AuditTrail/AuditTrailSearch";
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue(token_.GetValue());
                StringContent content = new StringContent(JsonConvert.SerializeObject(data), Encoding.UTF8, "application/json");
                using (var response = await client.PostAsync(url, content))
                {
                    string res = await response.Content.ReadAsStringAsync();
                    list = JsonConvert.DeserializeObject<List<Audittrailvm>>(res);
                }
            }
            catch (Exception ex)
            {
                string status = ex.GetBaseException().ToString();
            }
            return Json(list);
        }
        [HttpPost]
        public async Task<IActionResult> GetDataAuditTrailList(paginate data)
        {
            string result = "";
            var list = new List<AuditTrailPaginationModel>();
            try
            {
                HttpClient client = new HttpClient();
                var url = DBConn.HttpString + "/api/ApiPagination/AuditTrailPaginate";
                //var url = DBConn.HttpString + "/api/ApiAuditTrail/AudittrailList";
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue(token_.GetValue());
                StringContent content = new StringContent(JsonConvert.SerializeObject(data), Encoding.UTF8, "application/json");
                using (var response = await client.PostAsync(url, content))
                {
                    string res = await response.Content.ReadAsStringAsync();
                    list = JsonConvert.DeserializeObject<List<AuditTrailPaginationModel>>(res);

                }
            }

            catch (Exception ex)
            {
                string status = ex.GetBaseException().ToString();
            }
            return Json(list);
        }
        [HttpGet]
        public async Task<JsonResult> GetAuditTrailList()
        {
            //var url = DBConn.HttpString + "/api/AuditTrail/AudittrailList";
            var url = DBConn.HttpString + "/api/ApiAuditTrail/AudittrailList";
            HttpClient client = new HttpClient();
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token_.GetValue());
            string response = await client.GetStringAsync(url);
            List<Audittrailvm> models = JsonConvert.DeserializeObject<List<Audittrailvm>>(response);
            //return new(models);
            return Json(new { draw = 1, data = models, recordFiltered = models?.Count, recordsTotal = models?.Count });
        }

        public IActionResult Index()
        {
            string token = HttpContext.Session.GetString("Bearer");
            if (token == null || token == string.Empty)
            {
                return RedirectToAction("Index", "LogIn");
            }
            return View();
        }
        public IActionResult AuditTrail()
        {
            string token = HttpContext.Session.GetString("Bearer");
            if (token == null)
            {
                return RedirectToAction("Index", "LogIn");
            }
            return View();
        }

        #region DataModels

        public class Audittrailvm
        {

            public int Id { get; set; }
            public string Actions { get; set; }
            public string Module { get; set; }
            public string DateCreated { get; set; }
            public string status { get; set; }
            public string EmployeeID { get; set; }
            public string FullName { get; set; }
            public string Fname { get; set; }
            public string Lname { get; set; }
            public string PositionName { get; set; }
            public string CorporateName { get; set; }
            public string UserType { get; set; }
        }
        #endregion
    }
}

Views/CMS/AuditTrail.cshtml
@{
    ViewData["Title"] = "Audit Trail";
    Layout = "~/Views/Shared/_Layout.cshtml";
    string message = "";
    if (ViewData["Message"] != null)
    {
        message = ViewData["Message"].ToString();
    }

}
<style>
    .cust-pagination {
        display: flex;
        gap: 10px;
        justify-content: space-between;
        margin: 0px 50px 0px 40px;
    }

    .active-page {
        color: black !important;
    }

    #counter .tbl-pagenumber {
        color: #c89328;
        cursor: pointer;
        padding: 5px;
    }

    #prev {
        color: #c89328;
        cursor: pointer;
    }

    #next {
        color: #c89328;
        cursor: pointer;
    }

    table.myTableMedium tbody tr td:nth-child(3) p:nth-child(1) {
        width: 100px;
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
    }
</style>
@* <script src="https://cdn.datatables.net/2.1.8/js/dataTables.js"></script> *@

@* <link rel="stylesheet" href="https://cdn.datatables.net/2.1.8/css/dataTables.dataTables.css" /> *@

<link rel="stylesheet" href="/css/datatable.css" />
<script src="https://code.jquery.com/jquery-3.7.1.js"></script>
<script src="https://cdn.datatables.net/2.1.8/js/dataTables.js"></script>

<div class="register-main-container">
 
    <div class="card-header">
        <div class="row">
            <div class="list-title" style="border-radius:10px 10px 0px 0px">
                <h4 style="font-size: 26px;
                            display:flex;
                            gap: 5px;
                            align-items: center" 
                    class="text-left">
                    <svg xmlns="http://www.w3.org/2000/svg" height="34px" viewBox="0 -960 960 960" width="34px" fill="var(--light)"><path d="M280-600v-80h560v80H280Zm0 160v-80h560v80H280Zm0 160v-80h560v80H280ZM160-600q-17 0-28.5-11.5T120-640q0-17 11.5-28.5T160-680q17 0 28.5 11.5T200-640q0 17-11.5 28.5T160-600Zm0 160q-17 0-28.5-11.5T120-480q0-17 11.5-28.5T160-520q17 0 28.5 11.5T200-480q0 17-11.5 28.5T160-440Zm0 160q-17 0-28.5-11.5T120-320q0-17 11.5-28.5T160-360q17 0 28.5 11.5T200-320q0 17-11.5 28.5T160-280Z" /></svg>
                    @* <i class="fas fa-list"></i>  *@
                    @ViewData["Title"].ToString()
                </h4>
            </div>
        </div>
  

</div>
    <div class="tab-pane active " id="User">
                <br>
                <div class="card-body ">
                    <div class="row">

                        <div class="col-lg-12">

                            <div class="row ">
                        <div style="width: 100%; display: flex; justify-content: flex-end; margin: 10px 0; padding-right:40px">

                             @* <div>
                                 <label for="srchbox">Search Fullname</label>
                                 <input type="text" value="" id="srchbox" class="mod-input" />
                             </div> *@
                        </div>
                                <div id="register-table_wrapper" class="dataTables_wrapper no-footer" style="width:100%">
                                    <table id="audittrails-table" class="myTableMedium">
                                         <thead>
                                      
                                        <th>Employee ID</th>
                                        <th>Full Name</th>
                                        <th>Actions</th>
                                        <th>Module</th>
                                        <th>Position Name</th>
                                        <th>Corporate Name</th>
                                        <th>User Type</th>
                                        <th>Date Created</th>
                                    </thead>
                                    <tbody>

                                    </tbody>
                                    </table>
                             @* <div class="cust-pagination">
                                 <span id="prev">Prev</span>
                                 <div id="counter"></div>
                                 <span id="next">Next</span>
                             </div> *@
                               </div>
                            </div>
                        </div>

                      
                       
                    </div>
                </div>
            </div>
    </div>
@* End here *@
@section Scripts{
    <script>
          i_id=0;
        var prev = 0;
        var next = 0;
        var spanval = "";
        var currpage = "";
        var data = {};
        $(document).ready(function () {
            getAuditTrail();
        });
        function getAuditTrail() {
            new DataTable('#audittrails-table', {
                ajax: {
                    url: '@Url.Action("GetAuditTrailList", "CMS")',
                    type: "GET",
                    dataType: "json",
                    processing: true,
                    serverSide: true,
                    complete: function (xhr) {
                        // console.log(xhr);
                    },
                    error: function (err) {
                        alert(err.responseText);
                    }
                },
                columns: [
                    {
                        data: 'employeeID'
                    },
                    {
                        data: 'fullName'
                    },
                    {
                        data: 'actions'
                    },
                    {
                        data: 'module'
                    },
                    {
                        data: 'positionName'
                    },
                    {
                        data: 'corporateName'
                    },
                    {
                        data: 'userType'
                    },
                    {
                        data: 'dateCreated'
                    }
                ]
            });
        }
</script>
}

        